name: chipseq
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - fastqc=0.12.1
  - multiqc=1.14
  - trim-galore=0.6.10
  - bowtie2=2.5.1
  - samtools=1.17
  - picard=3.0.0
  - macs2=2.2.9.1
  - bedtools=2.31.0
  - ucsc-bedgraphtobigwig=447
  - deeptools=3.5.2
  - sra-tools=3.0.7
  - r-base=4.2
  - r-tidyverse
  - r-ggplot2
  - r-pheatmap
  - bioconductor-chipseeker
  - bioconductor-clusterprofiler
  - bioconductor-org.mm.eg.db
  - bioconductor-txdb.mmusculus.ucsc.mm10.knowngene
  - wget
  - pigz
